version: '3.7'
services:
  node_sentiment:
    build: 
      context: .
    container_name: node_sentiment
    # network_mode: host
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    depends_on:
      - redis
      - mysql
    ports:
      - 8080:8080
    networks:
      - node_sentiment
  redis:
    image: redis:6.2.6-alpine
    container_name: redis_node_sentiment
    ports:
      - 6379:6379
    networks:
      - node_sentiment
  mysql:
    image: mariadb:10.7
    container_name: mysql_node_sentiment
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=node_sentiment
    volumes:
      - node_sentiment:/var/lib/mysql
    networks:
      - node_sentiment
  phpmyadmin:
    image: phpmyadmin:5.1.3-apache
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8181:80
    networks:
      - node_sentiment
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=secret
networks:
  node_sentiment:
volumes:
  node_sentiment: