version: '3.7'
services:
  node_sentiment:
    build: 
      context: .
    container_name: node_sentiment
    network_mode: host
    volumes:
      - "./:/usr/src/app"
    restart: on-failure
    depends_on:
      - redis
    # ports:
    #   - 8080:8080
    # networks:
    #   - node_sentiment
  redis:
    image: redis:6.2.6-alpine
    container_name: redis_node_sentimet
    ports:
      - 6379:6379
    # networks:
    #   - node_sentiment